### PR TITLE
moved quickcheck and arbitrary impls to test-only

### PR DESCRIPTION
**Pull request by rrichardson**
Regex and therefore quickcheck is unstable, so in order to build regularly, need to move this to test only.

### CODE REVIEW

**Comment by cgaebel** [comment]
Bah. I just wanted to provide an arbitrary instance for people to test things. I don't actually use it in any iobuf tests. :( I guess I'll just back it out.

**Comment by rrichardson** [comment]
hang on. I have fixes for uint/usize too :)

**Comment by rrichardson** [comment]
we can actually put it back, because I think the regex instability is
mostly over..

**Comment by rrichardson** [comment]
I am still getting: 
```
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/DebugInfo.cpp:159: uint64_t llvm::DIVariable::getPieceOffset() const: Assertion `isVariablePiece()' failed.
Could not compile `regex`.
```

When I compile tests (quickcheck) brings in the dependency, but something is still breaking regex.

**Comment by cgaebel** [comment]
Yeah I get that too. No idea what's doing that. I may just drop the quick check stuff.

**Comment by rrichardson** [comment]
How does one tell travis to try to rebuild (now that he has a newer rust) ?

**Comment by cgaebel** [comment]
I generally just add 2 commits: one adding an empty file and one removing it.

**Comment by rrichardson** [comment]
Closing this in favor of #6

**Pull request closed without merging**
